### PR TITLE
test trigger rebuild

### PR DESCRIPTION
**Pull request by osamples**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by osamples** [comment]
@conda-forge-admin, please rerender

**Comment by osamples** [comment]
@izahn this one is just a rerendering and it passed all checks

**Comment by izahn** [comment]
I think we already have a working build, is this PR needed?

**Comment by osamples** [comment]
this was to make it available in the [conda-forge feedstocks ](https://conda-forge.org/feedstock-outputs/)

**Comment by izahn** [comment]
Hmm not sure why it doesn't show up there. It is in the repository though: https://anaconda.org/conda-forge/dedupe

and I can install it as usual:

```
$ conda install -c conda-forge dedupe                                                                                                        (base) 
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/izahn/mambaforge

  added / updated specs:
    - dedupe


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    affinegap-1.11             |   py39h3811e60_1          19 KB  conda-forge
    btrees-4.9.2               |   py39h3811e60_1         661 KB  conda-forge
    categorical-distance-1.9   |     pyhd8ed1ab_0           7 KB  conda-forge
    datetime-distance-0.1.3    |     pyhd8ed1ab_0           8 KB  conda-forge
    dedupe-2.0.8               |   py39h3811e60_0         100 KB  conda-forge
    dedupe-hcluster-0.3.8      |   py39hce5d2b2_1         197 KB  conda-forge
    dedupe-variable-datetime-0.1.5|     pyhd8ed1ab_0           8 KB  conda-forge
    doublemetaphone-0.1        |py39he80948d_1004          23 KB  conda-forge
    fastcluster-1.1.26         |   py39hde0f152_3          48 KB  conda-forge
    haversine-2.5.1            |     pyhd8ed1ab_0           9 KB  conda-forge
    highered-0.2.1             |     pyhd8ed1ab_0           7 KB  conda-forge
    levenshtein-search-1.4.5   |   py39h3811e60_1          28 KB  conda-forge
    persistent-4.7.0           |   py39h3811e60_1         171 KB  conda-forge
    pyhacrf-datamade-0.2.5     |   py39hce5d2b2_1         217 KB  conda-forge
    pylbfgs-0.2.0.13           |   py39hce5d2b2_2          69 KB  conda-forge
    rlr-2.4.5                  |     pyhd8ed1ab_0          13 KB  conda-forge
    simplecosine-1.2           |     pyhd8ed1ab_0           7 KB  conda-forge
    typing-extensions-4.0.1    |       hd8ed1ab_0           8 KB  conda-forge
    zope.index-5.1.0           |   py39h3811e60_1         114 KB  conda-forge
    zope.interface-5.4.0       |   py39h3811e60_1         318 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         2.0 MB

The following NEW packages will be INSTALLED:

  affinegap          conda-forge/linux-64::affinegap-1.11-py39h3811e60_1
  btrees             conda-forge/linux-64::btrees-4.9.2-py39h3811e60_1
  categorical-dista~ conda-forge/noarch::categorical-distance-1.9-pyhd8ed1ab_0
  datetime-distance  conda-forge/noarch::datetime-distance-0.1.3-pyhd8ed1ab_0
  dedupe             conda-forge/linux-64::dedupe-2.0.8-py39h3811e60_0
  dedupe-hcluster    conda-forge/linux-64::dedupe-hcluster-0.3.8-py39hce5d2b2_1
  dedupe-variable-d~ conda-forge/noarch::dedupe-variable-datetime-0.1.5-pyhd8ed1ab_0
  doublemetaphone    conda-forge/linux-64::doublemetaphone-0.1-py39he80948d_1004
  fastcluster        conda-forge/linux-64::fastcluster-1.1.26-py39hde0f152_3
  haversine          conda-forge/noarch::haversine-2.5.1-pyhd8ed1ab_0
  highered           conda-forge/noarch::highered-0.2.1-pyhd8ed1ab_0
  levenshtein-search conda-forge/linux-64::levenshtein-search-1.4.5-py39h3811e60_1
  persistent         conda-forge/linux-64::persistent-4.7.0-py39h3811e60_1
  pyhacrf-datamade   conda-forge/linux-64::pyhacrf-datamade-0.2.5-py39hce5d2b2_1
  pylbfgs            conda-forge/linux-64::pylbfgs-0.2.0.13-py39hce5d2b2_2
  rlr                conda-forge/noarch::rlr-2.4.5-pyhd8ed1ab_0
  simplecosine       conda-forge/noarch::simplecosine-1.2-pyhd8ed1ab_0
  typing-extensions  conda-forge/noarch::typing-extensions-4.0.1-hd8ed1ab_0
  zope.index         conda-forge/linux-64::zope.index-5.1.0-py39h3811e60_1
  zope.interface     conda-forge/linux-64::zope.interface-5.4.0-py39h3811e60_1


Proceed ([y]/n)? 
```

**Comment by osamples** [comment]
oh okay that was always my initial check. ill close this out then!

**Pull request closed without merging**
